In [1]:
import numpy as np

In [4]:
#1차원 배열 생성
arrayld = np.array([1,2,3,4,5])
print("1차원배열:")
print(arrayld)
print(f"배열의 형태:{arrayld.shape}")
print("-"* 30)

#2차원 배열 생성
array2d = np.array([[1,2,3],[4,5,6]])
print("2차원 배열:")
print(array2d)
print(f"배열의 형태:{array2d.shape}")

1차원배열:
[1 2 3 4 5]
배열의 형태:(5,)
------------------------------
2차원 배열:
[[1 2 3]
 [4 5 6]]
배열의 형태:(2, 3)
